# Port to run on
server:
  port: ${port:8080}

# Our log file path and name
logging:
  file: logs/erc20-rest-service.log

# Endpoint of an Ethereum or Quorum node we wish to use.
# To use IPC simply provide a file path to the socket, such as /path/to/geth.ipc
nodeEndpoint: localhost:20000

# The Ethereum or Quorum address we wish to use when transacting.
# Note - this address must be already unlocked in the client
fromAddress: "0x167074ef05e6d33592aada6efce7b43c37f0292f"

credentials:
  password:
  source:
